# Netlify Build Settings
[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://restaurant-production-54bb.up.railway.app"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to backend (Railway backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://restaurant-production-54bb.up.railway.app/api/:splat"
  status = 200
  force = true
